server:
  address: localhost
  port: 8889
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12 # 启用http2
    key-store-password: 12345678 # 证书密码
    key-store-type: PKCS12 # 证书类型
    protocol: TLSv1.2 # 协议类型
    key-alias: undertow
spring:
  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
#  data:
    # independent MongoDB server
#    mongodb:
#      host: 154.8.171.18
#      port: 27017
#      username: admin
#      password: TC123456
#      database: admin