server:
  address: localhost
  port: 8081

# Thymeleaf 
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  # limit upload file size
  http:
    multipart.max-file-size: 1024KB
    max-request-size: 1024KB

# independent MongoDB server
#spring.data.mongodb.uri=mongodb://localhost:27017/test